### ISSUE TITLE
\Zend\Json\Json::prettyPrint fails for json containing string with commas

### ISSUE THREAD

**Issue by cezarykluczynski** [zendframework/zend-json#2]
Having the following JSON:

``` json
{ "key" : "Hello, world!" }
```

and parsing it using

``` php
\Zend\Json\Json::prettyPrint('{ "key" : "Hello, world!" }', ["indent" => ""]);
```

will produce:

``` php
{"key":"Hello,world!"}
```

The reason is first line from \Zend\Json\Json::prettyPrint

``` php
$tokens = preg_split('|([\{\}\]\[,])|', $json, -1, PREG_SPLIT_DELIM_CAPTURE);
```

not taking into account that a comma could resides inside a token.

**Comment by weierophinney** [comment]
Interestingly, this functionality can and likely should be removed at this point. `ext/json` is enabled by default in vanilla installs of PHP, and, since 5.4, supports pretty printing during `json_encode` if the `JSON_PRETTY_PRINT` flag is provided. Considering that all ZF components now only test and support PHP 5.5+, this method can and should just proxy to `return json_encode($data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);`

**Comment by Maks3w** [comment]
@weierophinney Proxy method can be targetted to 2.6 even 2.5.x. I don't see the BC break

**Comment by weierophinney** [comment]
@Maks3w Take a look at the code in both `Json::encode()` and `Json::prettyPrint()`; there are "features" we have currently that are not part of `ext/json`, such as what padding character(s) to use for pretty print that we would not be able to support. While it _shouldn't_ hamper interop, it _does_ represent a change in behavior, and hence the BC break if we go this route.

I've started work on it, and swapping the code in `prettyPrint()` to use `ext/json` immediately results in 3 failures, all of which are due to differences in how `ext/json` pretty prints vs the implementation in the class. I'm fine with changing the expectations, but that _does_ mean a BC break.

**Comment by Maks3w** [comment]
@weierophinney Ok as soon as a test fail probably will be a bc break :)

Do you will add ext/json to composer.json?

**Comment by weierophinney** [comment]
> Do you will add ext/json to composer.json?

We don't need to. It's a built-in; you have to go to remarkable efforts to disable it, and even most distributions that do the `--disable-all` and then provide packages for each extension usually bundle it regardless, or the default "metapackage" for PHP will include the package for it. It'd be like specifying `ext-pcre`; pointless.

**Comment by Maks3w** [comment]
But does not harm nothing add the extension, isn't?

**Comment by weierophinney** [comment]
Since it's not necessary, the simplest course is to leave it out.

**Comment by Maks3w** [comment]
Only after PHP 7 (https://wiki.php.net/rfc/jsond) the assumption of to be bundled is more safe

**Comment by localheinz** [comment]
Can confirm that this is the case!
